// Report
export const SET_PAGE = "SET_PAGE";
export const UPDATE_DATA_FROM_FETCH = "UPDATE_DATA_FROM_FETCH";
export const SET_LIMIT = "SET_LIMIT";

// Single
export const UPDATE_SINGLE_DATA_FROM_FETCH = "UPDATE_SINGLE_DATA_FROM_FETCH";
